# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Bio',       url: 'bio'}
- {name: 'News',      url: 'news'}
- {name: 'CV',        url: 'cv'}
- {name: 'Press',     url: 'press'}
- {name: 'Contact',   url: 'contact'}
- {name: 'Shop',      url: 'shop'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/juliaoldham'}
- {icon: 'instagram', link:  'https://www.instagram.com/juliaoldham/'}
- {icon: 'envelope', link:   'juliaoldham@gmail.com'}

# # Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'
